/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente.View;

import Cliente.Cliente;
import Cliente.Utilidades;
import Model.*;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisluna
 */
public class NuevaOferta extends javax.swing.JFrame {
    private ArrayList<SubastaInt> todasSubastas = new ArrayList<>();

    /**
     * Creates new form NuevaOferta
     */
    public NuevaOferta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        subastas = new javax.swing.JComboBox<>();
        monto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ofertar");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DecoType Naskh", 0, 18)); // NOI18N
        jLabel1.setText("Subasta:");

        jLabel2.setFont(new java.awt.Font("DecoType Naskh", 0, 18)); // NOI18N
        jLabel2.setText("Monto de la Oferta:");

        subastas.setFont(new java.awt.Font("DecoType Naskh", 0, 18)); // NOI18N

        monto.setFont(new java.awt.Font("DecoType Naskh", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("DecoType Naskh", 0, 18)); // NOI18N
        jButton1.setText("Ofertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(monto))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(257, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(subastas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(subastas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        actualizarSubastas();
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean ready = true;
        
        if (subastas.getSelectedItem().toString().equals("")) {
            ready = false;
            Utilidades.showWarning("Seleccione una subasta");
        }
        
        if (monto.getText().equals("")) {
            ready = false;
            Utilidades.showWarning("Debe especificar un monto");
        }
        
        
        if (ready) {
            try {
                int indexDeSubasta = subastas.getSelectedIndex();
                SubastaInt subasta = todasSubastas.get(indexDeSubasta);
                double montoA = Double.parseDouble(monto.getText());
                
              
                
                if (montoA <= Cliente.usuario.getSaldo()) { //Si tiene saldo para la oferta
                    
                    if (subasta.ofertar(Cliente.usuario, montoA)) {
                        Utilidades.showMessage("Oferta Puesta");
                        this.dispose();
                    } else {
                        Utilidades.showWarning("Error al hacer oferta en metodo de subasta");
                    }
                    
                    
                    
                                   
                } else {
                    Utilidades.showWarning("No dispone de saldo suficiente para realizar esta oferta");
                }
 
            } catch (Exception ex) {
                ex.printStackTrace();
                Utilidades.showWarning(ex.getMessage());
            }
            
            
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void actualizarSubastas () {
        
        System.out.println("Actualizando Subastas...");
        try {
            
            DefaultComboBoxModel model = (DefaultComboBoxModel) subastas.getModel();
            
            for (SubastaInt s: Cliente.stub.subastas()) {
                
                System.out.println("Subasta en for: " + s.getProducto().getNombre());
                
                if(!s.getProducto().getDueno().getUsuario().equals(Cliente.usuario.getUsuario())) {
                    String tale = "";
                    
                    if(s.getUltimaOferta() != -1.0) {
                        tale = String.valueOf(s.getUltimaOferta());
                    } else {
                        tale = String.valueOf(s.getPrecio());
                    }
                    
                 
                    model.addElement(s.getProducto().getNombre() + " " + tale);
                    this.todasSubastas.add(s);
                    //model.addRow(new Object[]{s.getProducto().getNombre(), s.getPrecio(),s.getProducto().getDueno().getNombre(), lastOffer, status, new JButton("Ofertar") });
                    System.out.println(s.getProducto().getNombre());
                }
                
            }
                    
        } catch (RemoteException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaOferta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField monto;
    private javax.swing.JComboBox<String> subastas;
    // End of variables declaration//GEN-END:variables
}
