/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente.View;

import Cliente.*;
import Model.*;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisluna
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        subastas = new javax.swing.JTable();
        saludoLbl = new javax.swing.JLabel();
        onlineLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        enVenta = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usuariosActivos = new javax.swing.JTable();
        saldoLbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        misOfertas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        updateWindow = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        ofertar = new javax.swing.JMenuItem();
        aceptarSubasta = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ventana Principal :: UBay");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subastas En Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DecoType Naskh", 0, 18))); // NOI18N

        subastas.setFont(new java.awt.Font("DecoType Naskh", 0, 18)); // NOI18N
        subastas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio Inicial", "Vendedor", "Última Oferta", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        subastas.setCellSelectionEnabled(true);
        jScrollPane3.setViewportView(subastas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        saludoLbl.setFont(new java.awt.Font("DecoType Naskh", 0, 18)); // NOI18N
        saludoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        saludoLbl.setText("<Name>");

        onlineLbl.setFont(new java.awt.Font("DecoType Naskh", 0, 18)); // NOI18N
        onlineLbl.setText("En linea ❇");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mis Productos en Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DecoType Naskh", 0, 18))); // NOI18N

        enVenta.setFont(new java.awt.Font("DecoType Naskh", 0, 18)); // NOI18N
        enVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Última Oferta", "Comprador", "Estado"
            }
        ));
        jScrollPane5.setViewportView(enVenta);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios Activos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DecoType Naskh", 0, 18))); // NOI18N

        usuariosActivos.setFont(new java.awt.Font("DecoType Naskh", 0, 18)); // NOI18N
        usuariosActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Email"
            }
        ));
        jScrollPane2.setViewportView(usuariosActivos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );

        saldoLbl.setFont(new java.awt.Font("DecoType Naskh", 0, 18)); // NOI18N
        saldoLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        saldoLbl.setText("saldo");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mis Ofertas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DecoType Naskh", 0, 18))); // NOI18N

        misOfertas.setFont(new java.awt.Font("DecoType Naskh", 0, 18)); // NOI18N
        misOfertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Vendedor", "Mi Oferta", "Estado"
            }
        ));
        jScrollPane4.setViewportView(misOfertas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        );

        jMenu2.setText("Salir");

        exit.setText("Salir de UBay");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu2.add(exit);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Ventana");

        updateWindow.setText("Actualizar");
        updateWindow.setToolTipText("");
        updateWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWindowActionPerformed(evt);
            }
        });
        jMenu1.add(updateWindow);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Productos");

        jMenuItem1.setText("Crear Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem4.setText("Ver Comprados");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Subastas");

        jMenuItem2.setText("Crear Nueva");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        ofertar.setText("Ofertar");
        ofertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofertarActionPerformed(evt);
            }
        });
        jMenu4.add(ofertar);

        aceptarSubasta.setText("Aceptar Oferta");
        aceptarSubasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarSubastaActionPerformed(evt);
            }
        });
        jMenu4.add(aceptarSubasta);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(onlineLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saludoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(saldoLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saludoLbl)
                    .addComponent(onlineLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saldoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new NuevoProducto().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new ProductosComprados().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            this.usuariosActivos.setRowHeight(30);
            this.enVenta.setRowHeight(30);
            this.subastas.setRowHeight(30);
            this.misOfertas.setRowHeight(30);

            this.setLocationRelativeTo(null);
            this.setResizable(false);
            saludoLbl.setText("Bienvenido ! " + Cliente.usuario.getNombre());
            saldoLbl.setText("Saldo: $" + Cliente.usuario.getSaldo());
            actualizarTodo();

        } catch (RemoteException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void updateWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateWindowActionPerformed
        // TODO add your handling code here:
        this.actualizarMisOfertas();
    }//GEN-LAST:event_updateWindowActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //Terminar programa
        Cliente.exit();
    }//GEN-LAST:event_formWindowClosed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        Cliente.exit();
    }//GEN-LAST:event_exitActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new NuevaSubasta().setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ofertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofertarActionPerformed
        // TODO add your handling code here:
        new NuevaOferta().setVisible(true);
    }//GEN-LAST:event_ofertarActionPerformed

    private void aceptarSubastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarSubastaActionPerformed
        // TODO add your handling code here:
        new AceptarSubasta().setVisible(true);
    }//GEN-LAST:event_aceptarSubastaActionPerformed

    public void actualizarUsuariosActivos() {
        //System.out.println("Actualizando usuarios activos...");
        try {

            DefaultTableModel model = (DefaultTableModel) usuariosActivos.getModel();

            for (int i = 0; i < model.getRowCount(); i++) {
                model.removeRow(i);

            }
            if (Cliente.usuario == null) {
                System.err.println("**** Cliente.usuario IS  NULL *****");
                return;
            }

            for (UsuarioInt u : Cliente.stub.getUsuarios()) {

                if (!(u.getUsuario().equals(Cliente.usuario.getUsuario()))) {
                    System.out.println("Usuario activo 1: " + u.getNombre());
                    model.addRow(new Object[]{u.getNombre(), u.getEmail()});

                }

            }
            usuariosActivos.setModel(model);
            model.fireTableDataChanged();

        } catch (RemoteException ex) {
            Logger.getLogger(ProductosComprados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void actualizarTodo() {
        this.actualizarMisSubastas();
        this.actualizarTodasSubastas();
        this.actualizarUsuariosActivos();
        this.actualizarMisOfertas();
        this.actualizarSaldo();
    }

    public void actualizarSaldo() {
        try {
            if (Cliente.usuario == null) {
                return;
            }
            this.saldoLbl.setText(String.valueOf(Cliente.usuario.getSaldo()));
        } catch (RemoteException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void actualizarMisSubastas() {
        //System.out.println("Actualizando Subastas...");
        try {
            enVenta.removeAll();
            DefaultTableModel model = (DefaultTableModel) enVenta.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                model.removeRow(i);

            }

            for (SubastaInt s : Cliente.stub.subastas()) {
                
                if (s.getProducto().getDueno().getUsuario().equals(Cliente.usuario.getUsuario())) {

                    String lastOffer = "---";
                    //double Ultoferta;
                    if (s.getUltimaOferta() != -1.0) {
                        lastOffer = Double.toString(s.getUltimaOferta());
                    }

                    String comprador = s.getProducto().getDueno().getNombre();

                    //Checar si el comprador es el mismo es que no ha sido vendido, si es diferente ya fue vendido y el estado es "Vendido"
                    String status = "Activo";
                    String buyer = "---";
                    if (!s.getProducto().getDueno().equals(Cliente.usuario)) {
                        buyer = s.getProducto().getDueno().getNombre();
                        status = "Vendido";
                    }

                    model.addRow(new Object[]{s.getProducto().getNombre(), s.getPrecio(), lastOffer, buyer, status});
                   
                }

            }

        } catch (RemoteException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void actualizarTodasSubastas() {
        System.out.println("Actualizando todas Subastas...");
        try {
            
            DefaultTableModel model = (DefaultTableModel) subastas.getModel();
            
            for (int i = 0; i < model.getRowCount(); i++) {
                model.removeRow(i);

            }
            
             System.out.println("Numero de subastas en el servidor: (Ventana Princ)" + Cliente.stub.subastas().size());
            
            for (SubastaInt s: Cliente.stub.subastas()) {
                //System.out.println("Subasta en for: " + s.getProducto().getNombre());
                
                if(!s.getProducto().getDueno().getUsuario().equals(Cliente.usuario.getUsuario())) {
                    //System.out.println("Estoy dentro de if todas subastas: " + s.getProducto().getNombre());
                    
                    String lastOffer = "---";
                    //double Ultoferta;
                    if (s.getUltimaOferta() != -1.0) {
                       lastOffer = Double.toString(s.getUltimaOferta());
                    }
                    
                    String comprador = s.getProducto().getDueno().getNombre();
                    
                    //Checar si el comprador es el mismo es que no ha sido vendido, si es diferente ya fue vendido y el estado es "Vendido"
                    String status = "Activo";
                    String buyer = "---";
                    if (!s.getProducto().getDueno().equals(Cliente.usuario)) {
                        buyer = s.getProducto().getDueno().getNombre();

                    } else {
                        status = "Vendido";
                    }
                    
                    
                    
                    model.addRow(new Object[]{s.getProducto().getNombre(), s.getPrecio(),s.getProducto().getDueno().getNombre(), lastOffer, status });
                    //System.out.println("En model de todas subastas hay: " + model.getRowCount());
                    subastas.setModel(model);
                    model.fireTableDataChanged();
                }
                
            }
                    
        } catch (RemoteException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    public void actualizarMisOfertas() {
        System.out.println("Actualizando Mis Ofertas...");
        try {

            DefaultTableModel model = (DefaultTableModel) misOfertas.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                model.removeRow(i);

            }

            for (SubastaInt s : Cliente.stub.subastas()) {
               
               
                for (Oferta o : s.getOfertas()) {
                   
                    if (o.ofertante.getUsuario().equals(Cliente.usuario.getUsuario())) {
                        
                        //Checar si el comprador es el mismo es que no ha sido vendido, si es diferente ya fue vendido y el estado es "Vendido"
                        String status = "Activo";

                        if (s.getProducto().getDueno().equals(Cliente.usuario)) {

                            status = "Vendido";
                        }

                        model.addRow(new Object[]{o.producto.getNombre(), o.producto.getDueno().getNombre(), o.oferta,status});
                        

                    }

                }
            }

        } catch (RemoteException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aceptarSubasta;
    private javax.swing.JTable enVenta;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable misOfertas;
    private javax.swing.JMenuItem ofertar;
    private javax.swing.JLabel onlineLbl;
    private javax.swing.JLabel saldoLbl;
    private javax.swing.JLabel saludoLbl;
    private javax.swing.JTable subastas;
    private javax.swing.JMenuItem updateWindow;
    private javax.swing.JTable usuariosActivos;
    // End of variables declaration//GEN-END:variables
}
